# Generated by Django 4.2.7 on 2026-04-08 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_recurring',
            field=models.BooleanField(default=False, help_text='Check if this event repeats weekly.'),
        ),
        migrations.AddField(
            model_name='event',
            name='is_suspended',
            field=models.BooleanField(default=False, help_text='Temporarily suspend the recurrence (holidays, summer break, etc.).'),
        ),
        migrations.AddField(
            model_name='event',
            name='recurrence_day',
            field=models.IntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='Day of the week on which the event repeats.', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='recurrence_duration_minutes',
            field=models.IntegerField(blank=True, help_text='Duration in minutes (optional).', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='recurrence_time',
            field=models.TimeField(blank=True, help_text='Start time of the recurring event.', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='suspended_until',
            field=models.DateField(blank=True, help_text='Automatically resume from this date. Leave blank to suspend indefinitely.', null=True),
        ),
    ]
