# Generated by Django 4.2.7 on 2026-04-08 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_event_recurrence'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registration_info',
            field=models.TextField(blank=True, help_text='Instructions for registration: contact person, phone, link, deadline, etc.'),
        ),
    ]
