# Generated by Django 4.2.7 on 2026-04-10 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_event_registration_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='has_communion',
            field=models.BooleanField(default=False, help_text='Check if nattvard (communion) is part of this event.'),
        ),
        migrations.AddField(
            model_name='event',
            name='has_sunday_school',
            field=models.BooleanField(default=False, help_text='Check if Söndagsskolan (Sunday school) takes place during this event.'),
        ),
    ]
