# Generated by Django 4.2.7 on 2026-04-10 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_historyentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyentry',
            name='leaders',
            field=models.JSONField(blank=True, default=list, help_text="List of leader strings, e.g. 'Georg Steen 1919–1921'"),
        ),
    ]
