# Generated by Django 4.2.7 on 2026-04-13 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_secondhandstore_donation_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secondhandstore',
            name='opening_hours',
            field=models.JSONField(blank=True, default=list, help_text='List of {day, hours} objects, e.g. [{"day": "Måndag", "hours": "10:00–16:00"}]'),
        ),
    ]
