# Generated by Django 4.2.7 on 2026-04-14 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_announcement_add_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlphaProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hero_eyebrow', models.CharField(default='Pingstkyrkan Elim · Trelleborg', max_length=200)),
                ('hero_title', models.CharField(default='Alpha', max_length=200)),
                ('hero_subtitle', models.TextField(default='Utforska livet, tron och meningen — i en öppen och välkomnande atmosfär där alla frågor är välkomna.')),
                ('intro_quote', models.CharField(default='En plats där du kan utforska livet, tron och meningen.', max_length=300)),
                ('intro_body', models.TextField(default='Alpha är en kostnadsfri kurs på ca 13 veckor där vi samlas för att samtala kring de stora frågorna i livet. Vem är Jesus? Finns Gud? Vad händer efter döden? Vi möts i en avslappnad atmosfär med god mat, film och samtal — utan press och utan förväntningar. Du behöver ingen förkunskap. Det enda som krävs är nyfikenhet.')),
                ('intro_image', models.ImageField(blank=True, null=True, upload_to='alpha/')),
                ('video_url', models.URLField(blank=True, default='https://www.youtube.com/embed/HTCwMn6LKCI?rel=0&modestbranding=1')),
                ('video_title', models.CharField(blank=True, default='Vad är Alpha?', max_length=200)),
                ('steps', models.JSONField(blank=True, default=list, help_text='List of {emoji, title, desc} objects')),
                ('topics', models.JSONField(blank=True, default=list, help_text='List of topic strings')),
                ('next_alpha_tag', models.CharField(blank=True, default='Nästa Alpha', max_length=100)),
                ('next_alpha_title', models.CharField(blank=True, default='Välkommen med under vårterminen!', max_length=200)),
                ('next_alpha_desc', models.TextField(blank=True, default='Vi startar en ny omgång av Alpha snart. Kursen är gratis och öppen för alla — oavsett bakgrund, tro eller frågor. Anmäl dig eller kontakta oss för mer information om tid och plats.')),
                ('next_alpha_location', models.CharField(blank=True, default='Engelbrektsgatan 68, Trelleborg', max_length=200)),
                ('next_alpha_email', models.EmailField(blank=True, default='pingstkyrkan.trelleborg@gmail.com', max_length=254)),
                ('closing_quote', models.TextField(blank=True, default='"Alpha är en plats där du kan vara precis den du är — med alla dina frågor, tvivel och tankar."')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'alpha_program',
            },
        ),
        migrations.CreateModel(
            name='AlphaPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='alpha/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('alpha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='core.alphaprogram')),
            ],
            options={
                'db_table': 'alpha_photos',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
