# Generated by Django 4.2.7 on 2026-04-16 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_team_member_seed'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreTeensContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_name', models.CharField(default='Sleep Over', help_text='Name of the upcoming event shown in the countdown', max_length=200)),
                ('event_datetime', models.DateTimeField(help_text='Date and time of the event (used for the countdown timer)')),
                ('photo', models.ImageField(blank=True, help_text='Photo shown in the bento grid', null=True, upload_to='preteens/')),
            ],
            options={
                'verbose_name': 'Pre-Teens Content',
                'db_table': 'preteens_content',
            },
        ),
        migrations.AlterField(
            model_name='teammember',
            name='role_title',
            field=models.CharField(blank=True, help_text="Displayed role title, e.g. 'Pastor & föreståndare'", max_length=100),
        ),
    ]
