# Generated by Django 4.2.7 on 2026-04-16 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_preteens_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preteenscontent',
            options={'ordering': ['event_datetime'], 'verbose_name': 'Pre-Teens Event', 'verbose_name_plural': 'Pre-Teens Events'},
        ),
    ]
