# Generated by Django 4.2.7 on 2026-04-20 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_preteens_multi'),
    ]

    operations = [
        migrations.CreateModel(
            name='UngdomarNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tag', models.CharField(help_text="Short label e.g. 'Nyhet', 'Event', 'Läger'", max_length=80)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='ungdomar/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Ungdomar News',
                'verbose_name_plural': 'Ungdomar News',
                'db_table': 'ungdomar_news',
                'ordering': ['-created_at'],
            },
        ),
    ]
