# Generated by Django 4.2.7 on 2026-04-20 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_ungdomar_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreTeensNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tag', models.CharField(max_length=80)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='preteens_news/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Pre-Teens News',
                'verbose_name_plural': 'Pre-Teens News',
                'db_table': 'preteens_news',
                'ordering': ['-created_at'],
            },
        ),
    ]
